### ISSUE TITLE
REQUEST: New membership for XJangel

### ISSUE THREAD

**Issue by XJangel** [kubeedge/community#10]
## GitHub Username

@XJangel
## Organization you are requesting membership in

@kubeedge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors

@fisherxu 
@kevin-wangzefeng 
## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#1443
kubeedge/kubeedge#1640
fisherxu/kubeedge#7

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
Another  PR in my repo:
https://github.com/fisherxu/kubeedge/pull/7

**Comment by XJangel** [comment]
> Another PR in my repo:
> [fisherxu/kubeedge#7](https://github.com/fisherxu/kubeedge/pull/7)

get it !

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, looking forward to more of your contributions.

**Comment by fisherxu** [comment]
I think the invitation has been accepted, close the issue now :)
/close
