### ISSUE TITLE
REQUEST: New membership for <your name>

### ISSUE THREAD

**Issue by pengbinbin1** [kubeedge/community#100]
## GitHub Username

@pengbinbin1
## Organization you are requesting membership in

kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/edgemesh/pull/364
https://github.com/kubeedge/edgemesh/pull/357
https://github.com/kubeedge/edgemesh/pull/331
https://github.com/kubeedge/kubeedge/pull/3250
https://github.com/kubeedge/kubeedge/pull/3419
- Issues authored:
https://github.com/kubeedge/edgemesh/issues/314
https://github.com/kubeedge/edgemesh/issues/318
https://github.com/kubeedge/edgemesh/issues/155
https://github.com/kubeedge/edgemesh/issues/224
https://github.com/kubeedge/edgemesh/issues/145
https://github.com/kubeedge/kubeedge/issues/3416
- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1 Thanks for the contributions :) cc  @Poorunga

**Comment by Poorunga** [comment]
+1

**Comment by pengbinbin1** [comment]
@fisherxu Can you send an invitation for me?

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please check your email or visit https://github.com/kubeedge to confirm and join

**Comment by pengbinbin1** [comment]
@kevin-wangzefeng  Can you  send an invitation for me again? Because I do not  enabled [two-factor authentication] on my GitHub account at that time so can not see the invitation now. And I have  enabled [two-factor authentication] on my GitHub account recently.thank you!

**Comment by pengbinbin1** [comment]
@fisherxu

**Comment by pengbinbin1** [comment]
thank you
