### ISSUE TITLE
REQUEST: New membership for GsssC

### ISSUE THREAD

**Issue by GsssC** [kubeedge/community#11]
## GitHub Username
 @GsssC
 
 ## Organization you are requesting membership in
 @kubeedge
 
 ## Requirements
 * [x]  I have reviewed the [community membership guidelines](https://github.com/kubeedge/community/blob/master/community-membership.md)
 * [x]  I have enabled [two-factor authentication](https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication) on my GitHub account
 * [x]  I am actively contributing to 1 or more KubeEdge subprojects
 * [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
 
 ## Sponsors
 @fisherxu
 @kevin-wangzefeng
 
 ## List of contributions to the KubeEdge project
 * PRs reviewed / authored:
   [kubeedge/kubeedge#1600](https://github.com/kubeedge/kubeedge/pull/1600)
   [kubeedge/kubeedge#1569](https://github.com/kubeedge/kubeedge/pull/1569)
   [kubeedge/kubeedge#1469](https://github.com/kubeedge/kubeedge/pull/1469)

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, looking forward to more of your contributions.

**Comment by GsssC** [comment]
thx
/close
