### ISSUE TITLE
REQUEST: New membership for my-git9

### ISSUE THREAD

**Issue by my-git9** [kubeedge/community#116]
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/4330
https://github.com/kubeedge/kubeedge/pull/4328
https://github.com/kubeedge/kubeedge/pull/4337
https://github.com/kubeedge/kubeedge/pull/4329
https://github.com/kubeedge/kubeedge/pull/3866
https://github.com/kubeedge/kubeedge/pull/3863
https://github.com/kubeedge/kubeedge/pull/4348
https://github.com/kubeedge/kubeedge/pull/4362
https://github.com/kubeedge/kubeedge/pull/4355
https://github.com/kubeedge/kubeedge/pull/4365
https://github.com/kubeedge/kubeedge/pull/4568
https://github.com/kubeedge/kubeedge/pull/4529

- Issues authored:
  https://github.com/kubeedge/kubeedge/issues/4361
- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by my-git9** [comment]
Hi  @gy95 @wackxu , can you sponsor me

**Comment by wackxu** [comment]
+1 Thanks for the contributions :)

**Comment by wackxu** [comment]
cc @fisherxu @kevin-wangzefeng

**Comment by gy95** [comment]
+1

**Comment by my-git9** [comment]
I have received the invitation message, thanks for all
