### ISSUE TITLE
REQUEST: New membership for daixiang0

### ISSUE THREAD

**Issue by daixiang0** [kubeedge/community#12]
## GitHub Username
@daixiang0

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@kevin-wangzefeng

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
[kubeedge/kubeedge#1625](https://github.com/kubeedge/kubeedge/pull/1625)
[kubeedge/kubeedge#1628](https://github.com/kubeedge/kubeedge/pull/1628)
[kubeedge/kubeedge#1636](https://github.com/kubeedge/kubeedge/pull/1636)

- Issues authored:
[kubeedge/kubeedge#1623](https://github.com/kubeedge/kubeedge/issues/1623)
[kubeedge/kubeedge#1624](https://github.com/kubeedge/kubeedge/issues/1624)
[kubeedge/kubeedge#1629](https://github.com/kubeedge/kubeedge/issues/1629)
[kubeedge/kubeedge#1637](https://github.com/kubeedge/kubeedge/issues/1637)

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

Invitation sent.
