### ISSUE TITLE
REQUEST: New membership for JiaweiGithub

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/community#121]
## GitHub Username

JiaweiGithub
## Organization you are requesting membership in

kubeedge
## Requirements

> * [x]  I have reviewed the [community membership guidelines](https://github.com/kubeedge/community/blob/master/community-membership.md)
> * [x]  I have joined in the community [mailing list](https://groups.google.com/forum/#!forum/kubeedge) and [slack](https://kubeedge.slack.com/)
> * [x]  I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list](https://github.com/kubeedge/kubeedge/watchers))
> * [x]  I have enabled [two-factor authentication](https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication) on my GitHub account
> * [x]  I am actively contributing to 1 or more KubeEdge subprojects
> * [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
> * [x]  I have checked my affiliation in [devstats](https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1) (if it's not correct, please fix in [cncf/gitdm](https://github.com/cncf/gitdm#addingupdating-affiliation))

## Sponsors

@fisherxu @gy95 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/4262#issuecomment-1276929323
https://github.com/kubeedge/kubeedge/pull/4261#event-7476105165
https://github.com/kubeedge/kubeedge/pull/4304#event-7577122284
https://github.com/kubeedge/edgemesh/pull/467
https://github.com/kubeedge/edgemesh/pull/457
https://github.com/kubeedge/edgemesh/pull/468
https://github.com/kubeedge/edgemesh/pull/473
https://github.com/kubeedge/edgemesh/pull/477
https://github.com/kubeedge/kubeedge/pull/4714
https://github.com/kubeedge/kubeedge/pull/4809
https://github.com/kubeedge/website/pull/321

- Issues authored:
https://github.com/kubeedge/edgemesh/issues/356
https://github.com/kubeedge/edgemesh/issues/471
https://github.com/kubeedge/edgemesh/issues/459
https://github.com/kubeedge/kubeedge/issues/4653
https://github.com/kubeedge/kubeedge/issues/4750
https://github.com/kubeedge/kubeedge/issues/4695
https://github.com/kubeedge/kubeedge/issues/3952
https://github.com/kubeedge/kubeedge/issues/4822

- Issues responded to:
https://github.com/kubeedge/kubeedge/pull/4142#issuecomment-1275609255
- Other contributions:
[Attended the KubeEdge Academic Workshop  and shared topics
](https://www.huaweicloud.com/lab/edgecloud/news/news_20221115.html)

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
Please list two Sponsors who have reviewed your PR, and the Sponsors need to comment like `+1` here. :) @JiaweiGithub

**Comment by JiaweiGithub** [comment]
> Please list two Sponsors who have reviewed your PR, and the Sponsors need to comment like `+1` here. :) @JiaweiGithub

done

**Comment by JiaweiGithub** [comment]
@kevin-wangzefeng  @fisherxu @Poorunga  @vincentgoat    Please help comment+1

**Comment by Poorunga** [comment]
+1 :)

**Comment by kevin-wangzefeng** [comment]
Invited, you'll be receiving an email shortly. You can also visit https://github.com/kubeedge to accept the invitation.
