### ISSUE TITLE
REQUEST: New membership for <jxs1211>

### ISSUE THREAD

**Issue by jxs1211** [kubeedge/community#125]
## GitHub Username
@jxs1211

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe to updates (My account appears in the [watchers list])
- [ ] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix it in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- https://github.com/kubeedge/kubeedge/pull/4489
- https://github.com/kubeedge/kubeedge/pull/4467
- https://github.com/kubeedge/kubeedge/pull/4461

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
@jxs1211 Thanks for your contributions! And please list at two Sponsors who helped review and merge your PR, and let them comment `+1` here, and I'd like to sponsor you!

**Comment by fisherxu** [comment]
+1

**Comment by jxs1211** [comment]
> 



> @jxs1211 Thanks for your contributions! And please list at least two Sponsors who helped review and merge your PR, and let them comment `+1` here, and I'd like to sponsor you!

gotcha

**Comment by vincentgoat** [comment]
+1

**Comment by jxs1211** [comment]
Thanks, @vincentgoat, and @fisherxu.
Hi, @kevin-wangzefeng 
There are still some [PRs](https://github.com/kubeedge/kubeedge/pulls/jxs1211) have already been reviewed and updated, please reference those PRs if the PRs in the list of contributions are supposed to be insufficient.

**Comment by kevin-wangzefeng** [comment]
Invited, you'll be receiving an email shortly. You can also visit https://github.com/kubeedge to accept the invitation.
