### ISSUE TITLE
REQUEST: New membership for Piwriw

### ISSUE THREAD

**Issue by Piwriw** [kubeedge/community#139]
## GitHub Username

@Piwriw
## Organization you are requesting membership in

KubeEdge
## Requirements

- [✔ ] I have reviewed the [community membership guidelines]
- [ ✔] I have joined in the community [mailing list] and [slack]
- [ ✔] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [✔ ] I have enabled [two-factor authentication] on my GitHub account
- [✔ ] I am actively contributing to 1 or more KubeEdge subprojects
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ✔] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored: 
https://github.com/kubeedge/examples/pull/136
https://github.com/kubeedge/examples/pull/134
https://github.com/kubeedge/website/pull/298
https://github.com/kubeedge/website/pull/303

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/4638
https://github.com/kubeedge/sedna/issues/395

- Issues responded to:
https://github.com/kubeedge/kubeedge/issues/4589
https://github.com/kubeedge/kubeedge/issues/4661
- other:
Certification and Award of Excellence:https://github.com/kubeedge/community/issues/141

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by Piwriw** [comment]
@vincentgoat ,@Shelley-BaoYue Will you be my sponsors?

**Comment by vincentgoat** [comment]
+1

**Comment by Shelley-BaoYue** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
@Piwriw Invitation sent, please visit https://github.com/kubeedge or find link from email notification to confirm and join.

**Comment by Piwriw** [comment]
Thanks @Shelley-BaoYue @vincentgoat

**Comment by Piwriw** [comment]
> @Piwriw Invitation sent, please visit https://github.com/kubeedge or find link from email notification to confirm and join.

I will check it.Thanks.
