### ISSUE TITLE
REQUEST: New membership for fujitatomoya

### ISSUE THREAD

**Issue by fujitatomoya** [kubeedge/community#140]
## GitHub Username

fujitatomoya https://github.com/fujitatomoya

## Organization you are requesting membership in

KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project

- PRs reviewed / authored:

https://github.com/pulls?q=is%3Apr+author%3Afujitatomoya+archived%3Afalse+kubeedge

- Issues authored:

https://github.com/issues?q=is%3Aissue+author%3Afujitatomoya+archived%3Afalse+kubeedge

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fujitatomoya** [comment]
> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Actually no against this requirement.

@fisherxu would you mind being the sponsor of me?

**Comment by fisherxu** [comment]
+1 Thanks for your contributions for KubeEdge! :)

**Comment by fujitatomoya** [comment]
All checkpoints are green. if anything else needs to be addressed on my side, let me know.

**Comment by fujitatomoya** [comment]
Friendly ping?

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions, please visit https://github.com/kubeedge to accept the invitation.
