### ISSUE TITLE
REQUEST: New membership for <wjmstf1>

### ISSUE THREAD

**Issue by wjmstf1** [kubeedge/community#143]
## Requirements

- [ ] I have reviewed the [community membership guidelines]
- [ ] I have joined in the community [mailing list] and [slack]
- [ ] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [ ] I have enabled [two-factor authentication] on my GitHub account
- [ ] I am actively contributing to 1 or more KubeEdge subprojects
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
@wjmstf1 Could you please list your contributions for the community? Like code/issue/help other developers in community chat group or slack channel :) Thanks
