### ISSUE TITLE
REQUEST: New membership for Poor12

### ISSUE THREAD

**Issue by Poor12** [kubeedge/community#15]
## GitHub Username
@Poor12

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors
@fisherxu
@kevin-wangzefeng

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/1887
https://github.com/kubeedge/kubeedge/pull/1735
https://github.com/kubeedge/kubeedge/pull/1886
https://github.com/kubeedge/kubeedge/pull/1650

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/1692

**Comment by fisherxu** [comment]
+1 :)

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept the invitation.

**Comment by kevin-wangzefeng** [comment]
Closing as @Poor12 is now a KubeEdge member
/close
