### ISSUE TITLE
Apply for membership of cncf-kubeedge-distrib-announce@lists.cncf.io

### ISSUE THREAD

**Issue by WillardHu** [kubeedge/community#154]
_See [Private distributors list](https://github.com/kubeedge/community/blob/master/team-security/private-distributors-list.md#request-to-join) for additional places the request could be posted._

### 1. **Actively monitored security email alias for our project:**
kubeedge-security@daocloud.io

### 2. **Have a user base not limited to your own organization.**
DaoCloud Co,.Ltd. We contributes to the world's top open source projects for a long time, has an obvious leadership in many cloud-native projects such as Kubernetes, Istio, containerd, and more. DaoCloud is:
- The first cloud-native company that joined CNCF;
- One of the first CNCF-certified Kubernetes training partners;
- The only Chinese company with a contributing seat on the Istio Steering Committee;

### 3. **Have a publicly verifiable track record up to present day of fixing security issues.**
Have not yet fixed, but will continue to pay attention to the community security issues.

### 4. **Not be a downstream or rebuild of another distribution.**
No, DaoCloud doesn't hold a downstream nor rebuild of another distribution.

### 5. **Be a participant and active contributor in the community.**
Yes, we are often active in the KubeEdge community. https://kubeedge.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20quarter&var-metric=contributions

### 6. **Accept the [Embargo Policy](https://github.com/kubeedge/community/blob/master/team-security/private-distributors-list.md#embargo-policy).**
Yes, I agree

### 7. **Be willing to [contribute back](https://github.com/kubeedge/community/blob/master/team-security/private-distributors-list.md#contributing-back).**
Yes, when we receive a security issue, we will track it.

### 8. **Have someone already on the list vouch for the person requesting membership on behalf of your distribution.**
/assign @kubeedge/tsc

**Comment by kevin-wangzefeng** [comment]
Thanks @WillardHu for the application.
For the question `2. Have a user base not limited to your own organization.`, you may mention the product offering you are providing and some example customers you are serving

**Comment by WillardHu** [comment]
> Thanks @WillardHu for the application. For the question `2. Have a user base not limited to your own organization.`, you may mention the product offering you are providing and some example customers you are serving

Revised, thanks for guidance

**Comment by kevin-wangzefeng** [comment]
> 4. Not be a downstream or rebuild of another distribution.
> Yes

Just to be clear, you mean DaoCloud doesn't hold a downstream nor rebuild of another distribution, right?

There's some differences between Chinese and English on answering yes-or-no questions.

**Comment by WillardHu** [comment]
> > 4. Not be a downstream or rebuild of another distribution.
> >    Yes
> 
> Just to be clear, you mean DaoCloud's product is not a downstream nor rebuild of another distribution, right?
> 
> There's some differences between Chinese and English on answering yes-or-no questions.

Revised, thanks for guidance
