### ISSUE TITLE
REQUEST: New membership for luogangyi

### ISSUE THREAD

**Issue by luogangyi** [kubeedge/community#16]
## GitHub Username
[@luogangyi](https://github.com/luogangyi)

## Organization you are requesting membership in
[@kubeedge](https://github.com/kubeedge)

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

[@fisherxu](https://github.com/fisherxu)
[@kevin-wangzefeng](https://github.com/kevin-wangzefeng)

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
[extend property types ](https://github.com/kubeedge/kubeedge/pull/2014)
[workaround on cloudcore crash of device without nodeselector](https://github.com/kubeedge/kubeedge/pull/1916)
[Implement device management enhance](https://github.com/kubeedge/kubeedge/pull/1790)
[fix E2E_UPDATE_DEVICE_3 failure](https://github.com/kubeedge/kubeedge/pull/1709)
[support both RSA and DSA certificates](https://github.com/kubeedge/kubeedge/pull/1702)
[Add proposal for device management enhancement](https://github.com/kubeedge/kubeedge/pull/1687)
- Issues authored:
[extend device property types](https://github.com/kubeedge/kubeedge/issues/2013)
[cloudcore crash when no nodeSelector provide](https://github.com/kubeedge/kubeedge/issues/1913)
[Init websocket connection failed remote error: tls: handshake failure](https://github.com/kubeedge/kubeedge/issues/1699)
- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you can visit https://github.com/kubeedge to accept it.

**Comment by fisherxu** [comment]
Looks like the invitation has been accepted, close the issue now :)
/close
