### ISSUE TITLE
REQUEST: New membership for <tangming1996>

### ISSUE THREAD

**Issue by tangming1996** [kubeedge/community#164]
## GitHub Username

[tangming1996](https://github.com/tangming1996)
## Organization you are requesting membership in

@kubeedge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@kevin-wangzefeng 
@fisherxu 
@Shelley-BaoYue
@MooreZheng 
@jaypume 
@Poorunga 
@vincentgoat
@WillardHu

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/4911
https://github.com/kubeedge/kubeedge/pull/4867
https://github.com/kubeedge/kubeedge/pull/4859
https://github.com/kubeedge/kubeedge/pull/4854
https://github.com/kubeedge/sedna/pull/412
https://github.com/kubeedge/ianvs/pull/82
https://github.com/kubeedge/ianvs/pull/81

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/4861
https://github.com/kubeedge/kubeedge/issues/4860

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
@tangming1996 Please list at least two sponsors from different companies, and comment `+1` in this issue :) Thanks.

**Comment by tangming1996** [comment]
@kevin-wangzefeng @fisherxu @Shelley-BaoYue @Poorunga @vincentgoat Please help comment+1

**Comment by Shelley-BaoYue** [comment]
Please list sponsors here. 
![image](https://github.com/kubeedge/community/assets/48788150/7eaf2614-30b2-4bef-af40-a52c3f1df893)

**Comment by tangming1996** [comment]
> Please list sponsors here. ![image](https://user-images.githubusercontent.com/48788150/266518584-7eaf2614-30b2-4bef-af40-a52c3f1df893.png)

Ok, I have added, thank you.

**Comment by Shelley-BaoYue** [comment]
+1 
Thanks for your contributions!

**Comment by fisherxu** [comment]
+1
Thanks for your contributions!

**Comment by WillardHu** [comment]
+1
Thanks for your contributions!

**Comment by kevin-wangzefeng** [comment]
Thanks for your contribution, you may either check email notification or visit https://github.com/kubeedge to accept the invitation.
