### ISSUE TITLE
REQUEST: New membership for <zhiyingfang2022>

### ISSUE THREAD

**Issue by zhiyingfang2022** [kubeedge/community#167]
## GitHub Username

zhiyingfang2022
## Organization you are requesting membership in

@KubeEdge
## Requirements

- [X] I have reviewed the [community membership guidelines]
- [X] I have joined in the community [mailing list] and [slack]
- [X] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [X] I have enabled [two-factor authentication] on my GitHub account
- [X] I am actively contributing to 1 or more KubeEdge subprojects
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@kevin-wangzefeng 
@fisherxu
@Shelley-BaoYue
@WillardHu 
@JiaweiGithub 
## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/5015
https://github.com/kubeedge/kubeedge/pull/4655
https://github.com/kubeedge/website/pull/349

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by Shelley-BaoYue** [comment]
+1
Thanks for your contributions!

**Comment by fisherxu** [comment]
+1, thanks for the contributions :)
And the sponsors should come from at least two companies, please list one more sponsor who doesn't from huawei, thanks @zhiyingfang2022  :)

**Comment by WillardHu** [comment]
+1
Thanks for your contributions!

**Comment by JiaweiGithub** [comment]
+1
Thanks for your contributions!

**Comment by zhiyingfang2022** [comment]
> +1, thanks for the contributions :) And the sponsors should come from at least two companies, please list one more sponsor who doesn't from huawei, thanks @zhiyingfang2022 :)

Thanks,done.

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions.
Invitation sent, please visit https://github.com/kubeedge to accept the invitation.

**Comment by zhiyingfang2022** [comment]
> Thank you for your contributions. Invitation sent, please visit https://github.com/kubeedge to accept the invitation.

Thank you for your invitation .Already joined KubeEdge.
