### ISSUE TITLE
REQUEST: New membership for sailorvii

### ISSUE THREAD

**Issue by sailorvii** [kubeedge/community#17]
## GitHub Username
@sailorvii

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@kevin-wangzefeng 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/1917
https://github.com/kubeedge/kubeedge/pull/1940
https://github.com/kubeedge/kubeedge/pull/1952
https://github.com/kubeedge/kubeedge/pull/1946
https://github.com/kubeedge/kubeedge/pull/2025

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/1953
https://github.com/kubeedge/kubeedge/issues/1830

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
@sailorvii Invitation sent, you can visit @kubeedge to accept it.

**Comment by kadisi** [comment]
+1

**Comment by sailorvii** [comment]
Many thanks for you all.
