### ISSUE TITLE
REQUEST: New membership for wbc6080

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/community#171]
## GitHub Username

wbc6080 [https://github.com/wbc6080](https://github.com/wbc6080)
## Organization you are requesting membership in

KubeEdge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

 @fisherxu 
@Shelley-BaoYue 
@cl2017 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- https://github.com/kubeedge/kubeedge/pull/5068
- https://github.com/kubeedge/kubeedge/pull/5027
- https://github.com/kubeedge/kubeedge/pull/5026
- https://github.com/kubeedge/kubeedge/pull/5025
- https://github.com/kubeedge/kubeedge/pull/5023

- Issues authored:

- Issues responded to:
https://github.com/kubeedge/kubeedge/issues/5021
https://github.com/kubeedge/kubeedge/issues/5018

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
Please list at least two Sponsors that from two different companies, thanks :)

**Comment by cl2017** [comment]
+1 Thanks for your contributions!

**Comment by Shelley-BaoYue** [comment]
+1 Thanks for your contributions!

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions, invitation sent. You'll be receiving an email shortly. You can also visit https://github.com/kubeedge to accept the invitation.

**Comment by wbc6080** [comment]
I have received the invitation message, thanks a lot
/close
