### ISSUE TITLE
REQUEST: <Create> KubeRobo: Empowering RoboDevOps through Edge-Cloud Synergy

### ISSUE THREAD

**Issue by JoeyHwong-gk** [kubeedge/community#176]
### 1. **Name for new repository:**

KubeRobo

### 2. **Who should have admin access(subproject owners)?**

@Poorunga 
@fujitatomoya 

### 3. **Who should have write access?**

@fisherxu 
@kevin-wangzefeng 
@Poorunga 
@fujitatomoya 

### 4. **Who should be listed as approvers and reviewers in OWNERS?**

- approvers:
  - @fisherxu
  - @kevin-wangzefeng
  - @fujitatomoya 
  - @Poorunga
  
- reviewers:
  - @fisherxu
  - @kevin-wangzefeng
  - @fujitatomoya 
  - @Poorunga
  - @seveirbian
  - @JoeyHwong-gk 

### 5. **What should the repo description be?**

Repository for KubeEdge SIG Robotics: a Cloud-Native Robotics Management Solution, providing comprehensive descriptions of all SIG Robotics' open-source projects, including scope, features, and milestone.

### 6. **What SIG does this fall under?**

SIG Robotics

### 7. **Additional context for request.**

This repository will systematically showcase KubeRobo, the end-to-end cloud-native robotics solution by SIG Robotics. It will serve as a comprehensive guide to all open-source projects under SIG Robotics, covering their scopes, roadmaps, and feature plans.

**Comment by fujitatomoya** [comment]
@JoeyHwong-gk 

i am not really sure how this repo looks like... got a couple of questions though. is this repo URL would be like, https://github.com/kubeedge/kuberobo ? is it common that kubeedge has the dedicated repo for each SIG? i think there are going to be a bunch of CRD implementation for robots and aligned operators in this repo, with documentations for SIG robotics in this repo?

**Comment by JoeyHwong-gk** [comment]
> @JoeyHwong-gk
> 
> i am not really sure how this repo looks like... got a couple of questions though. is this repo URL would be like, https://github.com/kubeedge/kuberobo ? is it common that kubeedge has the dedicated repo for each SIG? i think there are going to be a bunch of CRD implementation for robots and aligned operators in this repo, with documentations for SIG robotics in this repo?

You're right; the repository I've requested might be found at [https://github.com/kubeedge/kuberobo](https://github.com/kubeedge/kuberobo). While 'kuberobo' stands for 'kubeedge for robotics,' I admit it's a bit of a mouthful. Naming has been quite a challenge for me. Do you have any suggestions?

Regarding the structure, having dedicated repositories for each SIG can vary based on organizational preferences. However, it's common to maintain a separate repository for each SIG or working group, aiding in managing their specific projects and documentation. This promotes clarity and organization within the broader GitHub organization.

Within the kuberobo repository, you'll find not only documentation specific to SIG Robotics but also the scope, roadmaps, and feature plans for all open-source projects under SIG Robotics (such as RoboDev, RoboSkill, RoboOperator – the ones we've been discussing). This structure ensures a clear delineation of responsibilities and resources related to SIG Robotics within the broader KubeEdge project.

**Comment by fisherxu** [comment]
`RoboDev, RoboSkill, RoboOperator` which will also be subprojects? If so, I think it should have some descriptions in the `Additional context`, and clarify them with `kuberobo`

**Comment by JoeyHwong-gk** [comment]
> `RoboDev, RoboSkill, RoboOperator` which will also be subprojects? If so, I think it should have some descriptions in the `Additional context`, and clarify them with `kuberobo`

Not exactly,  any open-source projects and work plans related to SIG Robotics are showcased here. This serves as a centralized hub, providing high-level proposals, events, and roadmaps. The specific implementation code will be included in the respective open-source projects. @seveirbian, feel free to jump in if there are any unclear expressions.

**Comment by seveirbian** [comment]
Kube Robo can be seen as a solution incubated by SIG Robotics. It logically links the work of SIG Robotics to the project and outlines the vision of the solution. It also serves as a portal to the solution and introduces specific projects, such as RoboDev, RoboSkill, and other possible projects. Specific projects will have their own repositories.

**Comment by seveirbian** [comment]
`KubeRobo can be seen as a solution` incubated by SIG Robotics. It logically links the work of SIG Robotics to the project and outlines the vision of the solution. It also serves as a portal to the solution and `introduces specific projects, such as RoboDev, RoboSkill, and other possible projects`. Specific projects will have their own code repositories.

**Comment by seveirbian** [comment]
`KubeRobo can be seen as a solution` incubated by SIG Robotics. It outlines the vision of the solution and logically links SIG Robotics' work together. It also serves as a portal and introduces specific projects, such as RoboDev, RoboSkill, and other possible projects. Specific projects will have their own repositories.

**Comment by fujitatomoya** [comment]
after all, i am okay to go with your idea and having the dedicated repository to proceed the development and discussion 1st place.

> While 'kuberobo' stands for 'kubeedge for robotics,' I admit it's a bit of a mouthful. Naming has been quite a challenge for me.

sorry, trying to be figuring out the requirements for robotics or robot custom resources to be developed here.

those CRDs will be dedicated to KubeEdge only? i thought those would be ones of k8s custom resources, which said we could use with k8s?
for example, the user wants to use robotics and robot custom resources to control robotics fleet from KubeEdge SIG repo, and they have k8s cluster in their own factory and logistics with many robots.
that is not the idea `Cloud Robotics` but it would be really useful if we could support those use cases with k8s as well.
what's in it for us is, number of users would be significantly different if we could support k8s users because everyone can use those robotics and robot custom resources to control the robotics fleet as long as they use k8s.

i may be mistaken on this since i am not yet familiar with KubeEdge `Cloud Robotics` requirement, but i guess it would be better to discuss on this requirement and rationals, since this could be impact for this project?

**Comment by JoeyHwong-gk** [comment]
> after all, i am okay to go with your idea and having the dedicated repository to proceed the development and discussion 1st place.
> 
> > While 'kuberobo' stands for 'kubeedge for robotics,' I admit it's a bit of a mouthful. Naming has been quite a challenge for me.
> 
> sorry, trying to be figuring out the requirements for robotics or robot custom resources to be developed here.
> 
> those CRDs will be dedicated to KubeEdge only? i thought those would be ones of k8s custom resources, which said we could use with k8s? for example, the user wants to use robotics and robot custom resources to control robotics fleet from KubeEdge SIG repo, and they have k8s cluster in their own factory and logistics with many robots. that is not the idea `Cloud Robotics` but it would be really useful if we could support those use cases with k8s as well. what's in it for us is, number of users would be significantly different if we could support k8s users because everyone can use those robotics and robot custom resources to control the robotics fleet as long as they use k8s.
> 
> i may be mistaken on this since i am not yet familiar with KubeEdge `Cloud Robotics` requirement, but i guess it would be better to discuss on this requirement and rationals, since this could be impact for this project?

Absolutely, for the CRDs, your considerations are valid. Currently, the plan is to have these CRDs dedicated to KubeEdge. However, your point about making them Kubernetes custom resources that can be used with any Kubernetes cluster is quite insightful.

But!!!  To avoid any misunderstanding, let me clarify. The repository I've requested, `KubeRobo`, is intended solely as an entry point to showcase all our sig open-source work proposals. As for the CRDs, they will indeed have independent repositories—possibly named `RoboOperator`. However, within `KubeRobo`, we'll strictly focus on presenting open-source projects, encompassing `RoboOperator`, `RoboDEV`,`RoboSkill `, and discussions, proposals, and roadmaps related to their creation and operation.

> So why not do this in the `Community` repository

That's a valid consideration. We did explore the option of consolidating work in the `Community` repository, as we've done in the past. However, after almost a year of operation, we identified some challenges. SIG Robotics aims to provide a comprehensive solution spanning the entire RoboDevOps process. Given the significant number of open-source projects involved, we want to create a more intuitive gateway, or a "portal" as I would like to define it, where practitioners interested in cloud-native robotics can easily find and engage with the specific projects they are interested in.

**Comment by fujitatomoya** [comment]
> let me clarify. The repository I've requested, KubeRobo, is intended solely as an entry point to showcase all our sig open-source work proposals.

understood. i dont have any other objections, thanks for the explanation.

**Comment by Poorunga** [comment]
Some individuals suggest that this project is a valuable paradigm for defining robot CRDs. Obtaining it is the embodiment of open source RoboOMS, and we can evolve it as the basic framework of kubebo

**Comment by Poorunga** [comment]
Here is a diagram that briefly summarizes the vision of SIG Robotics:
![87DD412C-1279-44BD-9F51-45919D454F54](https://github.com/kubeedge/community/assets/43004096/42a9184d-0290-4e21-9819-ea84a829c8e7)

**Comment by fisherxu** [comment]
+1 :)

**Comment by kevin-wangzefeng** [comment]
The KubeRobo repo is now available at: https://github.com/kubeedge/kuberobo, with repo admins, approvers and reviewers initialized.
