### ISSUE TITLE
REQUEST: New membership for wujunyi792

### ISSUE THREAD

**Issue by wujunyi792** [kubeedge/community#178]
## GitHub Username

wujunyi792 https://github.com/wujunyi792

## Organization you are requesting membership in

KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@Shelley-BaoYue 
@fisherxu 
@ttlv 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- https://github.com/kubeedge/kubeedge/pull/4914
- https://github.com/kubeedge/kubeedge/pull/4967
- https://github.com/kubeedge/kubeedge/pull/4968
- https://github.com/kubeedge/kubeedge/pull/5049

- Issues authored:
- https://github.com/kubeedge/kubeedge/issues/5124

- Issues responded to:
- https://github.com/kubeedge/kubeedge/issues/4408

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by Shelley-BaoYue** [comment]
Please add other sponsors from different companies/organizations

**Comment by Shelley-BaoYue** [comment]
+1 Thanks for your contributions!

**Comment by ttlv** [comment]
+1 Thanks for your contributions!

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
/close as @wujunyi792 has joined.
Welcome onboard!
