### ISSUE TITLE
REQUEST: New membership for Windrow14

### ISSUE THREAD

**Issue by Windrow14** [kubeedge/community#179]
## GitHub Username
Windrow14

## Organization you are requesting membership in
SONY

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@ZhengXinwei-F @fisherxu @fujitatomoya

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
  https://github.com/kubeedge/kubeedge/pull/5141
  https://github.com/kubeedge/kubeedge/pull/5143

- Issues authored:
  https://github.com/kubeedge/kubeedge/issues/5042

- Issues responded to:
  https://github.com/kubeedge/kubeedge/issues/4844
  https://github.com/kubeedge/kubeedge/issues/4843
  https://github.com/kubeedge/kubeedge/issues/3935

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1, Thanks for the contributions, plz list at least two sponsors who come from different companies, like @fujitatomoya can also be your  sponsor :)

**Comment by fujitatomoya** [comment]
👍 i second this.

**Comment by ZhengXinwei-F** [comment]
+1

**Comment by Windrow14** [comment]
> Thank you for your contribution, invitation sent, please visit https://github.com/kubeedge to accept the invitation.

Thanks for the invitation!
