### ISSUE TITLE
REQUEST: New membership for YaozhongZhang

### ISSUE THREAD

**Issue by YaozhongZhang** [kubeedge/community#18]
## GitHub Username

@YaozhongZhang

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@kadisi 
@fisherxu

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#1683
kubeedge/kubeedge#1787
kubeedge/kubeedge#1908
kubeedge/kubeedge#1914
kubeedge/kubeedge#1954
kubeedge/kubeedge#1963
kubeedge/kubeedge#2001
kubeedge/kubeedge#2033
kubeedge/kubeedge#2065
kubeedge/kubeedge#2086

- Issues authored:
kubeedge/kubeedge#1961 
kubeedge/kubeedge#2085

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please check your email. You can also visit https://github.com/kubeedge to accept the invitation.

**Comment by YaozhongZhang** [comment]
Thank you all. 
/close
