### ISSUE TITLE
REQUEST: <Create> Mapper-Framework: Mapper Development Framework

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/community#180]
1. Name for new repository:
Mapper-Framework

2. Who should have admin access(subproject owners)?
@fisherxu
@kevin-wangzefeng

3. Who should have write access?
@cl2017
@fisherxu
@kevin-wangzefeng
@WillardHu

4. Who should be listed as approvers and reviewers in OWNERS?
approvers:
&emsp; @cl2017
&emsp; @fisherxu
&emsp; @kevin-wangzefeng
&emsp; @WillardHu
reviewers:
&emsp; @fisherxu
&emsp; @kevin-wangzefeng
&emsp; @cl2017 
&emsp; @wbc6080 
&emsp; @WillardHu

5. What should the repo description be?
Repository for KubeEdge Mapper Framework, providing Mapper development framework to quickly generate Mapper projects.

6. What SIG does this fall under?
SIG Device IoT

7. Additional context for request.
This repository will systematically demonstrate the development framework of Mapper in SIG Device IoT for managing user devices. It will cover the Mapper basic framework, usage guidance, and development plans. It can provide users with a convenient way to generate Mapper projects, allowing users to manage devices more efficiently.
At the same time, the development work of Mapper Framework is still carried out in the original directory（kubeedge/kubeedge/staging/src/github.com/kubeedge
/mapper-framework/）, but the latest modifications will be synchronized to this repository.

**Comment by fisherxu** [comment]
+1

**Comment by fujitatomoya** [comment]
sounds great 👍

**Comment by kevin-wangzefeng** [comment]
The repo is now available at: https://github.com/kubeedge/mapper-framework, with repo admins, approvers and reviewers initialized.
