### ISSUE TITLE
Migrate KubeEdge Slack to CNCF Slack workspace (https://slack.cncf.io)

### ISSUE THREAD

**Issue by fisherxu** [kubeedge/community#181]
## Why migrate

KubeEdge is now a CNCF incubating project, migrating slack to CNCF will make it easier to communicate with other communities, and CNCF's slack will also have more historical discussion records.

## How to migrate

We will follow the table below to migrate some channels to CNCF's slack. @fisherxu I will archive the channels on that schedule.

To join CNCF slack -> https://slack.cncf.io/

| Status | Channel        | Users | Date       | Migrator          | CNCF Channel                                                                 |
|--------|----------------|-------|------------|-------------------|------------------------------------------------------------------------------|
|        | general        | >1500 | 2023.11.30 | @fisherxu         | [kubeedge](https://cloud-native.slack.com/archives/C066UJZJKQE)              |
|        | dashboard      | <50   | 2023.11.30 | @fisherxu         | [kubeedge-dashboard](https://cloud-native.slack.com/archives/C066LNA3015)    |
|        | announcement   | >1000 | 2023.11.30 | @fisherxu         | [kubeedge-announcement](https://cloud-native.slack.com/archives/C067DTAF4Q1) |
|        | kubeedge-docs  | >1000 | 2023.11.30 | @fisherxu         | [kubeedge-docs](https://cloud-native.slack.com/archives/C06718RDHCJ)         |
|        | kubeedge-dev   | >1000 | 2023.11.30 | @fisherxu         | [kubeedge-dev](https://cloud-native.slack.com/archives/C06718TB6F4)          |
|        | sig-ai         | >50   | 2023.11.30 | @jaypume          | [kubeedge-sig-ai](https://cloud-native.slack.com/archives/C067DTGJJM7)       |
|        | sig-robotics   | 10    | 2023.11.30 | @Poorunga         | [kubeedge-sig-robotics](https://cloud-native.slack.com/archives/C066LNMUME3) |
|        | sig-device-iot | >100  | 2023.11.30 | @fisherxu         | [kubeedge-sig-device-iot](https://cloud-native.slack.com/archives/C067Q8J3KTJ)   |
|        | sig-security   | 15    | 2023.11.30 | @kevin-wangzefeng | [kubeedge-sig-security](https://cloud-native.slack.com/archives/C067Q8LC3T2) |
|        | sig-mec        | >100  | 2023.11.30 | @kevin-wangzefeng | [kubeedge-sig-mec](https://cloud-native.slack.com/archives/C06716458P5)      |
|        | summer-of-code | >100  | 2023.11.30 |                   | NA                                                                           |

## Migration tasks

- [x] Send out notifications in more community channels about the migration
- [x] Create corresponding Channels under CNCF slack workspace (once created, all users are recommended to start use the new slack channels)
- [x] #185
- [x] Change channel name in KubeEdge slack and export data including members list and public channel chat history
- [x] Import data to cncf slack workspace (we will need someone from CNCF admin team to help on this)

**Comment by kevin-wangzefeng** [comment]
Thanks @fisherxu for initiating this.
Also FYI to all the community members that this have been discussed among @kubeedge/tsc members, and we think the migration is helpful to improve community transparency and neutrality.

**Comment by fujitatomoya** [comment]
I'll second this, would be better for more exposure as well.

**Comment by kevin-wangzefeng** [comment]
Follow-up steps we need to do:

0. Send out notifications in more community channels about the migration
1. Create corresponding Channels under CNCF slack workspace (once created, all users are recommended to start use the new slack channels)
2. Update all slack relevant links, point to new address of KubeEdge slack channels
3. Change channel name in KubeEdge slack and export data including members list and public channel chat history
4. Import data to cncf slack workspace (we will need someone from CNCF admin team to help on this)

**Comment by kevin-wangzefeng** [comment]
Channels under CNCF workspace has been created:
- kubeedge https://cloud-native.slack.com/archives/C066UJZJKQE
- kubeedge-dashboard https://cloud-native.slack.com/archives/C066LNA3015
- kubeedge-announcement https://cloud-native.slack.com/archives/C067DTAF4Q1
- kubeedge-docs https://cloud-native.slack.com/archives/C06718RDHCJ
- kubeedge-dev https://cloud-native.slack.com/archives/C06718TB6F4
- kubeedge-sig-ai https://cloud-native.slack.com/archives/C067DTGJJM7
- kubeedge-sig-robotics https://cloud-native.slack.com/archives/C066LNMUME3
- kubeedge-device-iot https://cloud-native.slack.com/archives/C067Q8J3KTJ
- kubeedge-sig-security https://cloud-native.slack.com/archives/C067Q8LC3T2
- kubeedge-sig-mec https://cloud-native.slack.com/archives/C06716458P5

**Comment by fisherxu** [comment]
Archiving time of channels in KubeEdge workspace will be postponed to 11.30, to allow more users to have enough time to migrate.

**Comment by fujitatomoya** [comment]
@kevin-wangzefeng @fisherxu i would highly recommend that notification needs to be posted on each current channels on KubeEdge slack as well.

**Comment by fisherxu** [comment]
Sure, we will send the notification to each current channels this week :)
