### ISSUE TITLE
REQUEST: New membership for NicoleLeeuu

### ISSUE THREAD

**Issue by NicoleLeeuu** [kubeedge/community#182]
## GitHub Username

NicoleLeeuu https://github.com/NicoleLeeuu
## Organization you are requesting membership in

KubeEdge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu 
@Shelley-BaoYue 
@cl2017 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- [Mirgration solution for devices among multi-nodes](https://github.com/kubeedge/kubeedge/pull/5017)
- [[proposal] Migration Solution for Edge Devices among Multi-nodes](https://github.com/kubeedge/kubeedge/pull/4845)
- [fix typos in comments](https://github.com/kubeedge/kubeedge/pull/4278)

- Issues authored:
- [Can‘t pull the image of kubeedge/cloud-iptables-manager 1.13.0 when execute "keadm init" command](https://github.com/kubeedge/kubeedge/issues/4657)
- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by Shelley-BaoYue** [comment]
Please use [x] to select the check items in Requirements.

**Comment by NicoleLeeuu** [comment]
> Please use [x] to select the check items in Requirements.

Get it!

**Comment by Shelley-BaoYue** [comment]
+1 Thanks for your contributions!

**Comment by cl2017** [comment]
+1 Thanks for your contributions!

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions, invitation sent, please visit https://github.com/kubeedge to accept the invitation.
