### ISSUE TITLE
REQUEST: New membership for Onion-of-dreamed

### ISSUE THREAD

**Issue by Onion-of-dreamed** [kubeedge/community#183]
## GitHub Username

Onion-of-dreamed

## Organization you are requesting membership in

@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu 
@Shelley-BaoYue 
@kevin-wangzefeng 
@WillardHu
@JiaweiGithub 
@cl2017 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/5037
https://github.com/kubeedge/kubeedge/pull/5040
https://github.com/kubeedge/kubeedge/pull/5210
https://github.com/kubeedge/kubeedge/pull/5211
https://github.com/kubeedge/kubeedge/pull/5212
https://github.com/kubeedge/kubeedge/pull/5213

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/4723
https://github.com/kubeedge/kubeedge/issues/4866
https://github.com/kubeedge/kubeedge/issues/5197

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1 :)

**Comment by cl2017** [comment]
+1 Thanks for your contributions!

**Comment by Shelley-BaoYue** [comment]
+1 Thanks for your contributions!

**Comment by WillardHu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions, invitation sent, please visit https://github.com/kubeedge to accept the invitation.
