### ISSUE TITLE
REQUEST: New membership for cai6489

### ISSUE THREAD

**Issue by cai6489** [kubeedge/community#184]
## GitHub Username
cai6489 https://github.com/cai6489

## Organization you are requesting membership in
KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@Shelley-BaoYue
@cl2017

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- [Integrated redis and tdengine interfaces #5064](https://github.com/kubeedge/kubeedge/pull/5064)

- Issues authored:

- Issues responded to:

**Comment by kevin-wangzefeng** [comment]
Closing due to lack of follow-up updates, @cai6489  please feel free to reapply if you are interested in joinning.
/close
