### ISSUE TITLE
REQUEST: <Create> RoboLink: Driving Multi-Robot Scheduling with Unified Data Interface Standard

### ISSUE THREAD

**Issue by zhanghengsjtu** [kubeedge/community#187]
1. Name for new repository:
RoboLink

2. Who should have admin access(subproject owners)?
@zhanghengsjtu

3. Who should have write access?
@fisherxu
@kevin-wangzefeng
@zhanghengsjtu

4. Who should be listed as approvers and reviewers in OWNERS?
approvers:

@fisherxu
@kevin-wangzefeng
@zhanghengsjtu

reviewers:
@fisherxu
@kevin-wangzefeng
@zhanghengsjtu
@Poorunga
@seveirbian

5. What should the repo description be?
Repository for KubeEdge SIG Robotics: a unified data interface standard between cloud scheduling system and industrial mobile robot.

6. What SIG does this fall under?
SIG Robotics

7. Additional context for request.
This repository will systematically showcase RoboLink, the unified data interface standard proposed by **Huawei, Sinotrans，SF Express and other 30 partners**. It will serve as a comprehensive guide and also give an end-to-end scheduling system that adapts this interface.

**Comment by zhanghengsjtu** [comment]
As part of  [kuberobo](https://github.com/kubeedge/kuberobo), this repo is designed for connecting heterogeneous robots to cloud control platform. Currently, mobile robots are supported and we are happy to announce it. In the near future, more types of robots, such as manipulators, will be supported. Developers who are interested in this topic are welcome to join.

**Comment by JoeyHwong-gk** [comment]
Thank you for your contributions to SIG Robotics. I believe this is valuable work deserving community attention, and it aligns with my intentions. However, kindly remove my ID from the reviewer list as I currently don't have specific insights into this project. I will continue to monitor it and may join in when necessary.

1. Please ENSURE that the relevant members you've listed for have joined the community (as the role of **member**).
2. Kindly share your thoughts on this project in the upcoming **community meeting.**

/assign @Poorunga

**Comment by seveirbian** [comment]
+1 Thanks for your contributions!

**Comment by zhanghengsjtu** [comment]
Thank you @JoeyHwong-gk. I have removed your ID from the reviewer list, and i'm also looking forward to hear your visionary suggestions to this project in the future. Last but not least, very glad to introduce this project to the community in the upcoming meeting.

**Comment by fisherxu** [comment]
The owners/approvers/reviewers all should be members first, you can let them join as members first, or remove from the owners/approvers/reviewers list, re-join until become member in future. @zhanghengsjtu

**Comment by zhanghengsjtu** [comment]
@fisherxu . Thanks for your reminding. All the owners/approvers/reviewers are updated to make sure that they are members of kubeedge community.

**Comment by fisherxu** [comment]
Okey, sounds good.
/assign @fujitatomoya @JoeyHwong-gk  PTAL

**Comment by fisherxu** [comment]
cc @kubeedge/tsc  Please check to see if there are any other questions and suggestions.

**Comment by JoeyHwong-gk** [comment]
> the unified data interface standard proposed by Huawei, Sinotrans，SF Express and other 30 partners. 

/LGTM 
And just a simple suggestion for reference only. Please guide the partners to participate as reviewers during operation. : )

**Comment by seveirbian** [comment]
> > the unified data interface standard proposed by Huawei, Sinotrans，SF Express and other 30 partners.
> 
> /LGTM And just a simple suggestion for reference only. Please guide the partners to participate as reviewers during operation. : )

Thank you @JoeyHwong-gk for your suggestion, we will let partners participate more in the community in the future.

**Comment by kevin-wangzefeng** [comment]
The RoboLink repo is now available at https://github.com/kubeedge/robolink
