### ISSUE TITLE
REQUEST: New membership for zhanghengsjtu

### ISSUE THREAD

**Issue by zhanghengsjtu** [kubeedge/community#188]
## GitHub Username
@zhanghengsjtu

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@Poorunga
@seveirbian

## List of contributions to the KubeEdge project

- Issues authored: [RoboLink: Driving Multi-Robot Scheduling with Unified Data Interface Standard](https://github.com/kubeedge/community/issues/187)

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.io/docs/community/slack/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1, thanks for your contributions. And it's better to add another sponsor who is not from huawei :) @zhanghengsjtu

**Comment by JoeyHwong-gk** [comment]
+1 @zhanghengsjtu  gave a remarkable speech on behalf of sig robotics in [kubecon 2023](https://kccncosschn2023.sched.com/event/1PTJJ/kubeedgekai-zhen-chan-daepchuan-hui-ni-tan-jhoy-sailing-with-kubeedge-driving-multi-robot-scheduling-with-unified-data-interface-standard-heng-zhang-huawei), thanks for his contributions.

**Comment by tangming1996** [comment]
+1 Thanks for your contributions!

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visite https://github.com/kubeedge to confirm and join.
