### ISSUE TITLE
REQUEST: New membership for seveirbian

### ISSUE THREAD

**Issue by seveirbian** [kubeedge/community#189]
## GitHub Username
seveirbian https://github.com/seveirbian

## Organization you are requesting membership in
KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@Poorunga
@JiaweiGithub 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/edgemesh/pull/133

- Issues authored:

- Issues responded to:
https://github.com/kubeedge/community/issues/176

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.io/docs/community/slack/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1, thanks for your contributions.

**Comment by fisherxu** [comment]
And it's better to add another sponsor who is not from huawei :)

**Comment by JoeyHwong-gk** [comment]
@seveirbian  has advocated the work of sig robotics in past open source conferences and thanks him for his contributions. 
- [openi](https://2021.openi.org.cn)
- [chinaosc](https://chinaosc2023.ccf.org.cn/)

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visite https://github.com/kubeedge to confirm and join.

**Comment by seveirbian** [comment]
thank you
