### ISSUE TITLE
REQUEST: Create <api>: the canonical location of the KubeEdge API definition.

### ISSUE THREAD

**Issue by wbc6080** [kubeedge/community#193]
### 1. **Name for new repository:**
api

### 2. **Who should have admin access(subproject owners)?**
@kevin-wangzefeng 
@fisherxu 

### 3. **Who should have write access?**
@kevin-wangzefeng 
@fisherxu 
@WillardHu 
@Shelley-BaoYue 
@wbc6080 for sync codes from kubeedge/kubeedge

### 4. **Who should be listed as approvers and reviewers in OWNERS?**
approvers:
@kevin-wangzefeng 
@fisherxu 
@WillardHu 
@Shelley-BaoYue 
reviewers:
@kevin-wangzefeng 
@fisherxu 
@WillardHu 
@Shelley-BaoYue 
@wbc6080 

### 5. **What should the repo description be?**
Repository for KubeEdge API, providing KubeEdge standard API definition

### 6. **What SIG does this fall under?**
All related SIGs

### 7. **Additional context for request.**
This repository provides KubeEdge standard API definitions, such as device crd definition and cloudcore, edgecore configuration. During subsequent development, API changes will still be completed under the original path of the KubeEdge main repository(https://github.com/kubeedge/kubeedge/tree/master/staging/src/github.com/kubeedge), and the changes will be synchronized to the API repository later.

**Comment by kevin-wangzefeng** [comment]
Thanks for initiating this.

> During subsequent development, API changes will still be completed under the original path of the KubeEdge main repository(kubeedge/kubeedge/staging/src/github.com/kubeedge/api/), and the changes will be synchronized to the API repository later.

Is there a more formal location for this description? This is very important for people who would contribute to API, and release team members to make sure they add corresponding tag here when new releases cut in the main repo.

**Comment by wbc6080** [comment]
It should be located in https://github.com/kubeedge/kubeedge/tree/master/staging/src/github.com/kubeedge, I've updated it in the issue description. In addition, the api files have not been migrated to this directory yet. I will complete the migration as soon as possible.

**Comment by kevin-wangzefeng** [comment]
/lgtm
Thanks

**Comment by huanwei** [comment]
/lgtm
thanks

**Comment by kevin-wangzefeng** [comment]
We have got 5/7 (71.4%) binding LGTM from TSC members, let's go ahead to create the API repo.

**Comment by kevin-wangzefeng** [comment]
The API repository is alive at: https://github.com/kubeedge/api
