### ISSUE TITLE
REQUEST: New membership for cwl233

### ISSUE THREAD

**Issue by cwl233** [kubeedge/community#2]
### GitHub Username
@cwl233

### Organization you are requesting membership in
@kubeedge

### Requirements
- [x] I have reviewed the community membership guidelines 
(https://github.com/kubeedge/community/blob/master/community-membership.md)
- [x] I have enabled  two-factor authentication on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
### Sponsors
@fisherxu 
@kevin-wangzefeng 
@kadisi

### List of contributions to the KubeEdge project
- PRs  reviewed / authored:
https://github.com/kubeedge/kubeedge/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Acwl233+
- Issues authored:
https://github.com/kubeedge/kubeedge/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Acwl233+
- Issues responded to:
https://github.com/kubeedge/kubeedge/issues/1288
https://github.com/kubeedge/kubeedge/issues/1263

**Comment by fisherxu** [comment]
+1，thanks for your contributions, hope for more activities in the future :)

**Comment by kevin-wangzefeng** [comment]
+1, looking forward more of your contribution to the project :-)

**Comment by kevin-wangzefeng** [comment]
@cwl233 Invitation sent, please visit https://github.com/kubeedge to accept.

**Comment by kadisi** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
@cwl233 is now a @KubeEdge member, closing this issue.
/close
