### ISSUE TITLE
REQUEST: New membership for Shubham Singh

### ISSUE THREAD

**Issue by 1Shubham7** [kubeedge/community#205]
## GitHub Username
@1shubham7

## Organization you are requesting membership in
KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application [@Shelley-BaoYue  and @WillardHu]
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
- @Shelley-BaoYue  
- @WillardHu

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
**kubeedge/kubeedge**

1. [Moving from standard lib to `stretchr/testify` for UT](https://github.com/kubeedge/kubeedge/pull/5837)
2. [Test coverage for `cloud/cmd`](https://github.com/kubeedge/kubeedge/pull/5827)
3. [misspell in `schedule.yml`](https://github.com/kubeedge/kubeedge/pull/5814)
4. [Tests for `cloud/pkg/admissioncontroller` package](https://github.com/kubeedge/kubeedge/pull/5813)
5. [`Typed` tests](https://github.com/kubeedge/kubeedge/pull/5812)
6. [Added tests for `overridemanager` package](https://github.com/kubeedge/kubeedge/pull/5810)
7. [UTs for `commmandoverrider.go`](https://github.com/kubeedge/kubeedge/pull/5809)
8. [Test coverage for `cloud/pkg/dynamiccontroller` module](https://github.com/kubeedge/kubeedge/pull/5803)
9. [Added tests for `cloud/pkg/csidriver` pkg](https://github.com/kubeedge/kubeedge/pull/5795)
10. [Test coverage for `edge/pkg/metamanager/client` module - lease and node files](https://github.com/kubeedge/kubeedge/pull/5780)
11. [Added tests for pkgs in `kubernetes` module](https://github.com/kubeedge/kubeedge/pull/5778)
12. [Tests for `storage/v1` module](https://github.com/kubeedge/kubeedge/pull/5763)
13. [UT coverage for the `cloud/pkg/taskmanager/util` module](https://github.com/kubeedge/kubeedge/pull/5751)
14. [Small misspell](https://github.com/kubeedge/kubeedge/pull/5742)
15. [Test coverage for `cloud/cmd/admission` module](https://github.com/kubeedge/kubeedge/pull/5723)
16. [Test Coverage for `debug` package](https://github.com/kubeedge/kubeedge/pull/5708)
17. [Added tests for `keadm/cmd/keadm/app/cmd/debug/check.go`](https://github.com/kubeedge/kubeedge/pull/5700)
18. [Added tests for `keadm beta` and `cloud` packages](https://github.com/kubeedge/kubeedge/pull/5695)
19. [Test coverage for `keadm/cmd/keadm/app/cmd/ctl` module](https://github.com/kubeedge/kubeedge/pull/5693)
20. [Added test coverage for `pkg/stream` package](https://github.com/kubeedge/kubeedge/pull/5690)
21. [Unit tests for `cloud/pkg/cloudhub/common/helper.go`](https://github.com/kubeedge/kubeedge/pull/5687)
22. [Test coverage for `cloudstream` package](https://github.com/kubeedge/kubeedge/pull/5684)
23. [Added test coverage for `cloudstream.go`](https://github.com/kubeedge/kubeedge/pull/5682)
24. [Test coverage for `application.go`](https://github.com/kubeedge/kubeedge/pull/5675)

**kubeedge/website**

25. [New Blog for Release KubeEdge v1.10](https://github.com/kubeedge/website/pull/535)
26. [New Blog for Release KubeEdge v1.11](https://github.com/kubeedge/website/pull/538)
27. [New Blog for Release KubeEdge v1.12](https://github.com/kubeedge/website/pull/539)
28. [New Blog for Release KubeEdge v1.13](https://github.com/kubeedge/website/pull/542)
39. [New Blog for Release KubeEdge v1.14](https://github.com/kubeedge/website/pull/541)
30. [New Blog for Release KubeEdge v1.15](https://github.com/kubeedge/website/pull/579)
31. [New Blog for Release KubeEdge v1.17](https://github.com/kubeedge/website/pull/534)
32. [Bug: We need to fix some links for local development](https://github.com/kubeedge/website/pull/567)
33. [Docs: Improving the install with `keadm` documentation](https://github.com/kubeedge/website/pull/544)
34. [Replacing Twitter with X](https://github.com/kubeedge/website/pull/543)
35. [PR template goes inside `.github` directory](https://github.com/kubeedge/website/pull/537)

- Issues authored:

https://github.com/kubeedge/website/issues/533
https://github.com/kubeedge/website/issues/536
https://github.com/kubeedge/website/issues/533

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.io/docs/community/slack/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by 1Shubham7** [comment]
PTAL @Shelley-BaoYue I am not sure what to do with the "I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application" checkbox

**Comment by Shelley-BaoYue** [comment]
You can check `I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application` checkbox and then add me and @WillardHu under the sponsors. : )  Because we are familiar with the work you've done in the community.

**Comment by 1Shubham7** [comment]
done @Shelley-BaoYue : )

**Comment by 1Shubham7** [comment]
> Need add sponsors here： ![image](https://private-user-images.githubusercontent.com/48788150/365635913-106f1d76-19a7-47d8-ad41-47236d144901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODI1MjEsIm5iZiI6MTcyNTg4MjIyMSwicGF0aCI6Ii80ODc4ODE1MC8zNjU2MzU5MTMtMTA2ZjFkNzYtMTlhNy00N2Q4LWFkNDEtNDcyMzZkMTQ0OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDExNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDI4NmJhN2Q4MmUxYzg0YTQ3NGI3MjYxNTBlYmI2NjA3NTVlOTViNmQ4Zjc5OTk3MzQ3MGMyNTBkZGM0MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bCtoI309tD3GQjlnYjPwjsPzCGcLX8lNR3eiDOqQBqM)

ohh sorry, now done : )

**Comment by Shelley-BaoYue** [comment]
+1 
@1Shubham7  has done a lot work both in KubeEdge documentation and testing work. 👍

**Comment by WillardHu** [comment]
+1
Thanks for your contributions.

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions and welcome onboard!
Invitation sent, you can visit https://github.com/kubeedge to accept it.
