### ISSUE TITLE
REQUEST: Archive repo <kubeedge/viaduct>

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/community#206]
### 1. **Repository to archive:**

https://github.com/kubeedge/viaduct

### 2. **When should this be done?**

September 20th.

### 3. **Additional context for request.**

After research and dicussions on community meetings and TSC meetings, we have found that there are currently no scenarios for using [viaduct](https://github.com/kubeedge/viaduct) repository independently. To better maintain this part, we have decided to migrate viaduct directly to https://github.com/kubeedge/kubeedge/tree/master/pkg. 

I have also submitted an issue https://github.com/kubeedge/kubeedge/issues/5857 to track this migration.

**Comment by kevin-wangzefeng** [comment]
lgtm
This is helpful to simplify our repo management

**Comment by huanwei** [comment]
/lgtm
thanks

**Comment by fisherxu** [comment]
lgtm

**Comment by kevin-wangzefeng** [comment]
We have got 5/7 (71.4%) binding LGTM from TSC members, let's go ahead to archive the kubeedge/viaduct repo.

**Comment by fisherxu** [comment]
Close the issue as repo kubeedge/viaduct has been archived.
