### ISSUE TITLE
REQUEST: New membership for shenkonghui

### ISSUE THREAD

**Issue by shenkonghui** [kubeedge/community#23]
## GitHub Username
@shenkonghui

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu @GsssC

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/2009
https://github.com/kubeedge/kubeedge/pull/2098

- Issues authored:
https://github.com/kubeedge/kubeedge/issues/2006

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by GsssC** [comment]
+1 Thx for your contributioun ! : )

**Comment by fisherxu** [comment]
+1

**Comment by muxuelan** [comment]
I have no idea that I cann't open the link "mailing list".

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept.
