### ISSUE TITLE
REQUEST: New membership for muxuelan

### ISSUE THREAD

**Issue by muxuelan** [kubeedge/community#26]
## GitHub Username

@muxuelan
## Organization you are requesting membership in

@kubeedge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu
@kevin-wangzefeng
## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#2397
kubeedge/kubeedge#2396
kubeedge/kubeedge#2352
kubeedge/kubeedge#2341
kubeedge/kubeedge#2188

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept.
