### ISSUE TITLE
REQUEST: New membership for lvchenggang

### ISSUE THREAD

**Issue by lvchenggang** [kubeedge/community#29]
## GitHub Username
@lvchenggang

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu 
@kevin-wangzefeng 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#2108
kubeedge/kubeedge#2109
kubeedge/kubeedge#2116
kubeedge/kubeedge#2298
kubeedge/kubeedge#2310
kubeedge/kubeedge#2313
kubeedge/kubeedge#2329
kubeedge/kubeedge#2335
kubeedge/kubeedge#2336
kubeedge/kubeedge#2340
kubeedge/kubeedge#2343
kubeedge/kubeedge#2347
kubeedge/kubeedge#2389

- Issues authored:
kubeedge/kubeedge#2107

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
Thanks for your contributions, but looks like all your commits are commited with  unknow email address, so github can't count your contributions, you need to add the email addr in the commits to github profile setting. @lvchenggang  https://github.com/kubeedge/kubeedge/commits?author=lvchenggang

**Comment by lvchenggang** [comment]
> Thanks for your contributions, but looks like all your commits are commited with unknow email address, so github can't count your contributions, you need to add the email addr in the commits to github profile setting. @lvchenggang https://github.com/kubeedge/kubeedge/commits?author=lvchenggang

Now the problem should been solved.

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1
