### ISSUE TITLE
REQUEST: New membership for du2016

### ISSUE THREAD

**Issue by du2016** [kubeedge/community#3]
# GitHub Username

@du2016

# Organization you are requesting membership in

@kubeedge

# Requirements

- [x] I have reviewed the community membership guidelines,(https://github.com/kubeedge/community/blob/master/community-membership.md)

- [x]  I have enabled two-factor authentication on my GitHub account

- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

# Sponsors

@fisherxu 
@kadisi 

List of contributions to the KubeEdge project:

- PRs reviewed / authored:

https://github.com/kubeedge/kubeedge/pull/1270
https://github.com/kubeedge/kubeedge/pull/1278
https://github.com/kubeedge/kubeedge/pull/1275
https://github.com/kubeedge/kubeedge/pull/1265
https://github.com/kubeedge/kubeedge/pull/1344

- Issues responded to:

https://github.com/kubeedge/kubeedge/issues/1307#event-2860280191

**Comment by fisherxu** [comment]
+1, thanks for your contributions! :)

**Comment by kadisi** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Thanks @du2016 for your contribution to KubeEdge. Just to double check, have you joined in community slack and mailing list?

**Comment by du2016** [comment]
@kevin-wangzefeng yes,i have  joined in community slack and mailing list

**Comment by kevin-wangzefeng** [comment]
@du2016 Invitation sent, please visit https://github.com/kubeedge to accept.

**Comment by du2016** [comment]
thanks
