### ISSUE TITLE
REQUEST: New membership for gccio

### ISSUE THREAD

**Issue by gccio** [kubeedge/community#30]
## GitHub Username
@gccio

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu 
@kevin-wangzefeng 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
[https://github.com/kubeedge/kubeedge/pull/2486](https://github.com/kubeedge/kubeedge/pull/2486)
[https://github.com/kubeedge/kubeedge/pull/2480](https://github.com/kubeedge/kubeedge/pull/2480)
[https://github.com/kubeedge/kubeedge/pull/2469](https://github.com/kubeedge/kubeedge/pull/2469)
[https://github.com/kubeedge/kubeedge/pull/2468](https://github.com/kubeedge/kubeedge/pull/2468)
[https://github.com/kubeedge/kubeedge/pull/2463](https://github.com/kubeedge/kubeedge/pull/2463)
[https://github.com/kubeedge/kubeedge/pull/2460](https://github.com/kubeedge/kubeedge/pull/2460)
[https://github.com/kubeedge/kubeedge/pull/2454](https://github.com/kubeedge/kubeedge/pull/2454)
[https://github.com/kubeedge/kubeedge/pull/2415](https://github.com/kubeedge/kubeedge/pull/2415)
[https://github.com/kubeedge/kubeedge/pull/2304](https://github.com/kubeedge/kubeedge/pull/2304)
- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by gccio** [comment]
This pr [https://github.com/kubeedge/kubeedge/pull/2463](https://github.com/kubeedge/kubeedge/pull/2463) has also been merged.

**Comment by fisherxu** [comment]
+1 Thanks for the contributions :)

**Comment by kevin-wangzefeng** [comment]
+1 thanks for your contributions

**Comment by fisherxu** [comment]
@gccio Looks like you have accepted the invitation, close the issue now :)
/close
