### ISSUE TITLE
REQUEST: New membership for jaypume

### ISSUE THREAD

**Issue by jaypume** [kubeedge/community#34]
## GitHub Username
@jaypume 

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@llhuii
@fisherxu
@kevin-wangzefeng

## List of contributions to the KubeEdge project

- Initiate and organize KubeEdge SIG AI, and here is the [meeting notes] of KubeEdge SIG AI weekly meetings.
- Contributed the initial Sedna proposals and code. For details, see kubeedge/sedna#1.

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation
[meeting notes]: https://docs.google.com/document/d/12n3kGUWTkAH4q2Wv5iCVGPTA_KRWav_eakbFrF9iAww/edit#

**Comment by llhuii** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept.

**Comment by kevin-wangzefeng** [comment]
Applicant has now joined the org, closing.
/close
