### ISSUE TITLE
REQUEST: New membership for khalid-davis

### ISSUE THREAD

**Issue by khalid-davis** [kubeedge/community#35]
## GitHub Username

@khalid-davis
## Organization you are requesting membership in

@kubeedge
## Requirements

- [X] I have reviewed the [community membership guidelines]
- [X] I have joined in the community [mailing list] and [slack]
- [X] I have enabled [two-factor authentication] on my GitHub account
- [X] I am actively contributing to 1 or more KubeEdge subprojects
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@llhuii
@fisherxu
@kevin-wangzefeng

## List of contributions to the KubeEdge project
- Commits pulled:
   [kubeedge/sedna/commit/f33e138](https://github.com/kubeedge/sedna/commit/f33e138cfcae535281167f9a4887c6ade1436244)  
   [kubeedge/sedna/commit/1540f7e](https://github.com/kubeedge/sedna/commit/1540f7ecc76025737d100c63834998e1d8630044)
   [kubeedge/sedna/commit/595291e](https://github.com/kubeedge/sedna/commit/595291e5cd40b6bc3002517e55b6775a18d013bf)
  [kubeedge/sedna/commit/6072a66](https://github.com/kubeedge/sedna/commit/6072a66a11e892e37aba90b5c4378d7e5330ce4d)
  [kubeedge/sedna/commit/e5d5990](https://github.com/kubeedge/sedna/commit/e5d59903cf2923589190dd7beb129166fa2d9b5f)
- PRs reviewed / authored:

- Issues authored:

- Issues responded to:

- Discussion in KubeEdge SIG AI
  Share the model serving in [seldon-core](https://github.com/SeldonIO/seldon-core) On February 4th, 2021

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by llhuii** [comment]
+1. you can also list your discussion in KubeEdge SIG AI.

**Comment by khalid-davis** [comment]
ok @llhuii

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept.

**Comment by kevin-wangzefeng** [comment]
Applicant has now joined the org, closing.
/close
