### ISSUE TITLE
REQUEST: New membership for TymonXie

### ISSUE THREAD

**Issue by TymonXie** [kubeedge/community#36]
## GitHub Username
@TymonXie

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@llhuii
@fisherxu
@kevin-wangzefeng

## List of contributions to the KubeEdge project
- Commits pulled:
  [kubeedge/sedna/commit/4fa96ea](https://github.com/kubeedge/sedna/commit/4fa96eadfe9c49c683faaeb5030e180ef601aafd)
  [kubeedge/sedna/commit/b6bcd63](https://github.com/kubeedge/sedna/commit/b6bcd63c988ad572f63662ed6954f2da69a2de4c)
  [kubeedge/sedna/commit/43f7f78](https://github.com/kubeedge/sedna/commit/43f7f78e5972d572b839561b5c8f678880f74b30)
  [kubeedge/sedna/commit/5fec931](https://github.com/kubeedge/sedna/commit/5fec9314cd1d2e270808df431ad3fee6aa306426)
  [kubeedge/sedna/commit/9df636f](https://github.com/kubeedge/sedna/commit/9df636f435d3de368a0de44869366bfceee886fa)

- PRs reviewed / authored:

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by llhuii** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept.

**Comment by kevin-wangzefeng** [comment]
Applicant has now joined the org, closing.
/close
