### ISSUE TITLE
REQUEST: New membership for JimmyYang20

### ISSUE THREAD

**Issue by JimmyYang20** [kubeedge/community#37]
## GitHub Username
@JimmyYang20

## Organization you are requesting membership in
@Kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@llhuii
@fisherxu 
@kevin-wangzefeng 

## List of contributions to the KubeEdge project
- Commits pulled:
[kubeedge/sedna/commit/ec69ab0](https://github.com/kubeedge/sedna/commit/ec69ab0e16b4b328f76e3cef293fe8fb31ac0308)
[kubeedge/sedna/commit/37efbff](https://github.com/kubeedge/sedna/commit/37efbffed1bd11d3671075f925ecae2f21437cc6)
[kubeedge/sedna/commit/c4cfc1b](https://github.com/kubeedge/sedna/commit/c4cfc1bed7e11bdbcbff8abc51e93a22e967bed4)
[kubeedge/sedna/commit/5faa914](https://github.com/kubeedge/sedna/commit/5faa91402526d2abc63e886206442ce26140ad36)
[kubeedge/sedna/commit/8b0eb11](https://github.com/kubeedge/sedna/commit/8b0eb119214e5591e0165a46112605c389f4821a)
[kubeedge/sedna/commit/57cd9a1](https://github.com/kubeedge/sedna/commit/57cd9a142d1c25b334da1b86b8cce3ad69905c81)
[kubeedge/sedna/commit/f4fca6a](https://github.com/kubeedge/sedna/commit/f4fca6a8e449eafd4f284b98ffb009ecd7209353)
[kubeedge/sedna/commit/ab15aca](https://github.com/kubeedge/sedna/commit/ab15aca37e16baaf1e12c8117a4db45132b58b43)

- PRs reviewed / authored:

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by kevin-wangzefeng** [comment]
Please list your contributions in the application, thanks.

**Comment by llhuii** [comment]
+1

**Comment by JimmyYang20** [comment]
ok @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit [@kubeedge](https://github.com/kubeedge) to accept.

**Comment by kevin-wangzefeng** [comment]
Applicant has now joined the org, closing.
/close
