### ISSUE TITLE
REQUEST: New membership for Deepak Vij

### ISSUE THREAD

**Issue by deepak-vij** [kubeedge/community#39]
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [ ] I have joined in the community [mailing list] and [slack]
- [ ] I have enabled [two-factor authentication] on my GitHub account
- [ ] I am actively contributing to 1 or more KubeEdge subprojects
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:

- Issues authored: Yes

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by kevin-wangzefeng** [comment]
Hi @deepak-vij, as part of the process, please list your contributions and finish the check list. Thanks.
