### ISSUE TITLE
REQUEST: New membership for wzshiming

### ISSUE THREAD

**Issue by wzshiming** [kubeedge/community#44]
## GitHub Username
@wzshiming

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pulls?q=is%3Apr+author%3Awzshiming+
- Issues authored:
https://github.com/kubeedge/kubeedge/issues/created_by/wzshiming

**Comment by fisherxu** [comment]
+1 Thanks for the contributions.

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept it :-)

**Comment by wzshiming** [comment]
Thanks.
/close
