### ISSUE TITLE
REQUEST: New membership for kuramal

### ISSUE THREAD

**Issue by kuramal** [kubeedge/community#5]
##  GitHub Username
@kuramal

## Organization you are requesting membership in
@kubeedge

## Requirements
- [x] I have reviewed the community membership guidelines,(https://github.com/kubeedge/community/blob/master/community-membership.md)

 - [x] I have enabled two-factor authentication on my GitHub account

 - [x] I am actively contributing to 1 or more KubeEdge subprojects

- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors

@fisherxu
@kadisi

List of contributions to the KubeEdge project:
- PRs reviewed / authored:
[kubeedge/kubeedge#1339](https://github.com/kubeedge/kubeedge/pull/1339)
[kubeedge/kubeedge#1341](https://github.com/kubeedge/kubeedge/pull/1341)
[kubeedge/kubeedge#1346](https://github.com/kubeedge/kubeedge/pull/1346)
[kubeedge/kubeedge#1347](https://github.com/kubeedge/kubeedge/pull/1347)
[kubeedge/kubeedge#1350](https://github.com/kubeedge/kubeedge/pull/1350)
[kubeedge/kubeedge#1363](https://github.com/kubeedge/kubeedge/pull/1363)

**Comment by fisherxu** [comment]
Big +1, thanks for the contributions, look forward to more activities :)

**Comment by kadisi** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept the invitation.
