### ISSUE TITLE
REQUEST: New membership for <JoeyHwong-gk>

### ISSUE THREAD

**Issue by JoeyHwong-gk** [kubeedge/community#51]
## GitHub Username
@JoeyHwong-gk

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@ugvddm
@llhuii
@TymonXie
@jaypume 
@JimmyYang20

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
[kubeedge/sedna/pull/60](https://github.com/kubeedge/sedna/pull/60)
[kubeedge/sedna/pull/72](https://github.com/kubeedge/sedna/pull/72)
[kubeedge/sedna/pull/117](https://github.com/kubeedge/sedna/pull/117)
[kubeedge/sedna/pull/154](https://github.com/kubeedge/sedna/pull/154)
[kubeedge/sedna/pull/178](https://github.com/kubeedge/sedna/pull/178)
[kubeedge/sedna/pull/186](https://github.com/kubeedge/sedna/pull/186)
[kubeedge/community/pull/109](https://github.com/kubeedge/community/pull/109)
[kubeedge/community/pull/134](https://github.com/kubeedge/community/pull/134)
[kubeedge/community/pull/147](https://github.com/kubeedge/community/pull/147)
[kubeedge/community/pull/153](https://github.com/kubeedge/community/pull/153)

- Issues authored:
[kubeedge/sedna/issues/267](https://github.com/kubeedge/sedna/issues/267)
[kubeedge/sedna/issues/266](https://github.com/kubeedge/sedna/issues/266)
[kubeedge/sedna/issues/265](https://github.com/kubeedge/sedna/issues/265)
[kubeedge/sedna/issues/262](https://github.com/kubeedge/sedna/issues/262)
[kubeedge/sedna/issues/261](https://github.com/kubeedge/sedna/issues/261)
[kubeedge/sedna/issues/113](https://github.com/kubeedge/sedna/issues/113)
[kubeedge/sedna/issues/46](https://github.com/kubeedge/sedna/issues/46)

- Issues responded to:
[kubeedge/sedna/issues/294](https://github.com/kubeedge/sedna/issues/294)
[kubeedge/sedna/issues/241](https://github.com/kubeedge/sedna/issues/241)
[kubeedge/sedna/issues/194](https://github.com/kubeedge/sedna/issues/194)
[kubeedge/sedna/issues/151](https://github.com/kubeedge/sedna/issues/151)
[kubeedge/sedna/issues/133](https://github.com/kubeedge/sedna/issues/133)

- Additional 
1. I'm following community guidance and running sig robotics
2. I'm one of the developers of sedna (sig ai)
3. I'm a mentor to OSPP.

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by jaypume** [comment]
+1

**Comment by llhuii** [comment]
+1

**Comment by JimmyYang20** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to accept and join.
