### ISSUE TITLE
REQUEST: New membership for WintonChan

### ISSUE THREAD

**Issue by WintonChan** [kubeedge/community#52]
## GitHub Username
WintonChan

## Organization you are requesting membership in
kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
  [kubeedge/kubeedge#2593](https://github.com/kubeedge/kubeedge/pull/2593)
  [kubeedge/kubeedge#2588](https://github.com/kubeedge/kubeedge/pull/2588)
  [kubeedge/kubeedge#2516](https://github.com/kubeedge/kubeedge/pull/2516)
- Issues authored:

- Issues responded to:
  [kubeedge/kubeedge#2588](https://github.com/kubeedge/kubeedge/issues/2558)

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1
Please visit https://github.com/kubeedge to accept the invitation.
