### ISSUE TITLE
REQUEST: New membership for ZBoIsHere

### ISSUE THREAD

**Issue by ZBoIsHere** [kubeedge/community#55]
## GitHub Username
ZBoIsHere 

## Organization you are requesting membership in
KubeEdge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@kevin-wangzefeng 
@fisherxu 
@llhuii 
@Poorunga 
@jaypume 

## List of contributions to the KubeEdge project
- Community meeting shared topic:
[NAT Traversal in EdgeMesh via Hole Punching](https://docs.google.com/document/d/1Sr5QS_Z04uPfRbA7PrXr3aPwCRpx7EtsyHq7mp6CnHs/edit#heading=h.gx57c77yckqq)
[NAT Traversal demo and performance test based on libp2p](https://docs.google.com/document/d/1Sr5QS_Z04uPfRbA7PrXr3aPwCRpx7EtsyHq7mp6CnHs/edit#heading=h.v7e82vv0fcta)

- PRs reviewed / authored:
authored https://github.com/kubeedge/edgemesh/pull/22
reviewed https://github.com/kubeedge/edgemesh/pull/19

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by kevin-wangzefeng** [comment]
Please list your contributions, thanks

**Comment by llhuii** [comment]
+1

**Comment by jaypume** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to confirm and join
