### ISSUE TITLE
REQUEST: New membership for gy95

### ISSUE THREAD

**Issue by gy95** [kubeedge/community#57]
## GitHub Username

gy95
## Organization you are requesting membership in

KubeEdge
## Requirements

- [X] I have reviewed the [community membership guidelines]
- [X] I have joined in the community [mailing list] and [slack]
- [X] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [X] I have enabled [two-factor authentication] on my GitHub account
- [X] I am actively contributing to 1 or more KubeEdge subprojects
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/3021
https://github.com/kubeedge/kubeedge/pull/2995
https://github.com/kubeedge/kubeedge/pull/2964
- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by gy95** [comment]
ping @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Invitation sent, please visit https://github.com/kubeedge to accept the invitation.
