### ISSUE TITLE
REQUEST: New membership for chenchunxiu

### ISSUE THREAD

**Issue by chenchunxiu** [kubeedge/community#59]
## GitHub Username

@chenchunxiu

## Organization you are requesting membership in

@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@kevin-wangzefeng 
@fisherxu 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#3368
kubeedge/kubeedge#3277
kubeedge/kubeedge#3276
kubeedge/kubeedge#3275

- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visite https://github.com/kubeedge to confirm and join.

**Comment by kevin-wangzefeng** [comment]
Welcome on board, and looking forward to more of your contributions.
/close
