### ISSUE TITLE
REQUEST: New membership for jidalong

### ISSUE THREAD

**Issue by jidalong** [kubeedge/community#61]
## GitHub Username

@jidalong
## Organization you are requesting membership in

@kubeedge
## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu 
@kevin-wangzefeng 
## List of contributions to the KubeEdge project
- PRs reviewed / authored:
kubeedge/kubeedge#2182
kubeedge/kubeedge#2143
kubeedge/kubeedge#3346
kubeedge/kubeedge#3333
kubeedge/kubeedge#2143
kubeedge/kubeedge#3330
kubeedge/kubeedge#3353
kubeedge/kubeedge#3359

- Issues authored:
kubeedge/kubeedge#2810
kubeedge/kubeedge#3345
kubeedge/kubeedge#3057
- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by fisherxu** [comment]
+1

**Comment by fisherxu** [comment]
Looks like the invitation has been accepted. ：）
/close
