### ISSUE TITLE
REQUEST: New membership for zhu733756

### ISSUE THREAD

**Issue by zhu733756** [kubeedge/community#68]
## GitHub Username

@zhu733756

## Organization you are requesting membership in

https://github.com/kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu @zc2638 @gy95 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pulls?q=is%3Apr+author%3Azhu733756
- Issues authored:

- Issues responded to:

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1  ：）

**Comment by gy95** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visite https://github.com/kubeedge to confirm and join.

**Comment by zc2638** [comment]
+1

**Comment by zhu733756** [comment]
Thanks each Dalao@fisherxu @gy95 @kevin-wangzefeng @zc2638

**Comment by fisherxu** [comment]
Thanks for the great contributions to KubeEdge community @zhu733756. I'd like to nominate you as maintainer especially for cluster installation, cluster lifecycle areas.

**Comment by zhu733756** [comment]
> Thanks for the great contributions to KubeEdge community @zhu733756. I'd like to nominate you as maintainer especially for cluster installation, cluster lifecycle areas.

Thanks, it's my pleasure.
