### ISSUE TITLE
REQUEST: New membership for wackxu

### ISSUE THREAD

**Issue by wackxu** [kubeedge/community#70]
## GitHub Username
wackxu

## Organization you are requesting membership in
kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors

@fisherxu 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:

authored

https://github.com/kubeedge/kubeedge/pull/3675
https://github.com/kubeedge/kubeedge/pull/3658
https://github.com/kubeedge/kubeedge/pull/3646
https://github.com/kubeedge/kubeedge/pull/3689
https://github.com/kubeedge/kubeedge/pull/3685
https://github.com/kubeedge/kubeedge/pull/3665
https://github.com/kubeedge/kubeedge/pull/3664
https://github.com/kubeedge/kubeedge/pull/3637
https://github.com/kubeedge/kubeedge/pull/3576

reviewed 
https://github.com/kubeedge/kubeedge/pull/3700
https://github.com/kubeedge/kubeedge/pull/3508
https://github.com/kubeedge/kubeedge/pull/3670
https://github.com/kubeedge/kubeedge/pull/3707
https://github.com/kubeedge/kubeedge/pull/3678

- Issues authored:
(https://github.com/kubeedge/kubeedge/issues/3690)

- Issues responded to:
https://github.com/kubeedge/kubeedge/issues/3597

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visite https://github.com/kubeedge to confirm and join.
