### ISSUE TITLE
REQUEST: New membership for MooreZheng

### ISSUE THREAD

**Issue by MooreZheng** [kubeedge/community#76]
## GitHub Username
@MooreZheng

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@kevin-wangzefeng
@jaypume 
@JimmyYang20

## List of contributions to the KubeEdge project
- PRs reviewed:
https://github.com/kubeedge/sedna/pull/72
https://github.com/kubeedge/sedna/pull/116
https://github.com/kubeedge/sedna/pull/142
https://github.com/kubeedge/sedna/pull/178
https://github.com/kubeedge/sedna/pull/192
https://github.com/kubeedge/sedna/pull/233

- Issues authored:
https://github.com/kubeedge/sedna/issues/151
https://github.com/kubeedge/sedna/issues/275

- Issues responded to:
https://github.com/kubeedge/sedna/issues/96
https://github.com/kubeedge/sedna/issues/118
https://github.com/kubeedge/sedna/issues/119
https://github.com/kubeedge/sedna/issues/120
https://github.com/kubeedge/sedna/issues/231
https://github.com/kubeedge/sedna/issues/276
https://github.com/kubeedge/sedna/issues/298

- Other contributions:
[Established KubeEdge SIG AI with other partners and polished the SIG AI charter in 2020](https://github.com/kubeedge/community/blob/master/sig-ai/charter.md)
[Hosted routine weekly meetings in KubeEdge SIG AI in 2021 and 2022](https://docs.google.com/document/d/12n3kGUWTkAH4q2Wv5iCVGPTA_KRWav_eakbFrF9iAww/edit?usp=sharing) 
[Given 5+ talks personally and invited another 5+ professional talks on KubeEdge SIG AI and KubeEdge meetings in 2021 and 2022](https://space.bilibili.com/448816706/video)
[Served as a Team Leader to establish the new feature of Edge-cloud Collaborative Lifelong Learning in KubeEdge-Sedna in 2021](https://sedna.readthedocs.io/en/latest/proposals/lifelong-learning.html)
[Hosted an Edge AI Landing Chanllege Survey with KubeEdge SIG AI in 2021](https://bbs.huaweicloud.com/blogs/317787)
[Served as a Team Leader to working on the Edge AI Benchmarks in 2021 and 2022](https://github.com/MooreZheng/bench)
[Hosting Open Source Promotion Plan 2022 for KubeEdge](https://summer-ospp.ac.cn/#/org/orgdetail/98ab8bae-a41e-4282-a7bf-5a1c0fafd440/)
 

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
Looks like haven't listed the authored PR, which need at least  2 PRs

**Comment by fisherxu** [comment]
> According to the [membership docs](https://github.com/kubeedge/community/blob/master/community-membership.md), it says "Contributions may include, but are not limited to: Authoring PRs"etc. There are also members accepted without 2 authoring PRs in the past, as far as I am concerned.

+1  :)  I think I remembered the rules incorrectly, we appreciate all contributions to the community!

**Comment by kevin-wangzefeng** [comment]
+1
Invited, please visit https://github.com/kubeedge to accept the invitation.
