### ISSUE TITLE
REQUEST: New membership for RyanZhaoXB

### ISSUE THREAD

**Issue by RyanZhaoXB** [kubeedge/community#79]
## GitHub Username

RyanZhaoXB

## Organization you are requesting membership in

kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:

    * https://github.com/kubeedge/kubeedge/pull/3673
    * https://github.com/kubeedge/examples/pull/117
    * https://github.com/kubeedge/examples/pull/113
    * https://github.com/kubeedge/examples/pull/111
    * https://github.com/kubeedge/mappers-go/pull/67
    * https://github.com/kubeedge/mappers-go/pull/70
    * https://github.com/kubeedge/mappers-go/pull/68

- Issues authored:
    * https://github.com/kubeedge/kubeedge/issues/3760
    * https://github.com/kubeedge/kubeedge/issues/3804
    * https://github.com/kubeedge/kubeedge/issues/3895

- Issues responded to:
    * https://github.com/kubeedge/kubeedge/issues/3833
    * https://github.com/kubeedge/kubeedge/issues/3761
    * https://github.com/kubeedge/kubeedge/issues/3759
    * https://github.com/kubeedge/kubeedge/issues/3729
    * https://github.com/kubeedge/kubeedge/issues/3716
    * https://github.com/kubeedge/examples/issues/114
    * https://github.com/kubeedge/examples/issues/106
    * https://github.com/kubeedge/examples/issues/112

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by RyanZhaoXB** [comment]
@kevin-wangzefeng

**Comment by wackxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/kubeedge to confirm and join
