### ISSUE TITLE
REQUEST: New membership for FengyunPan2

### ISSUE THREAD

**Issue by FengyunPan2** [kubeedge/community#8]
## GitHub Username
@FengyunPan2

## Organization you are requesting membership in
@kubeedge

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing list] and [slack]
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## Sponsors
@fisherxu
@kevin-wangzefeng 

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
https://github.com/kubeedge/kubeedge/pull/1327
https://github.com/kubeedge/kubeedge/pull/1325
https://github.com/kubeedge/kubeedge/pull/1324
https://github.com/kubeedge/kubeedge/pull/1323
https://github.com/kubeedge/kubeedge/pull/1536

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent. Please visit https://github.com/kubeedge to accept.

**Comment by FengyunPan2** [comment]
Thx, 
/close
