### ISSUE TITLE
REQUEST: New membership for Congrool

### ISSUE THREAD

**Issue by Congrool** [kubeedge/community#85]
## GitHub Username

@Congrool

## Organization you are requesting membership in

@kubeedge

## Requirements

- [x] I have joined in the community [mailing list] and [slack]
- [x] I have reviewed the [community membership guidelines]
- [x] I have watched kubeedge/kubeedge on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more KubeEdge subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have checked my affiliation in [devstats] (if it's not correct, please fix in [cncf/gitdm])

## List of contributions to the KubeEdge project
- PRs reviewed / authored:
- kubeedge/kubeedge#1922
- kubeedge/kubeedge#1970
- kubeedge/kubeedge#1986
- kubeedge/kubeedge#3229
- kubeedge/kubeedge#3235
- kubeedge/kubeedge#3719
- kubeedge/kubeedge#3835

- Issues authored:
- kubeedge/kubeedge#1920
- kubeedge/kubeedge#1927
- kubeedge/kubeedge#1958
- kubeedge/kubeedge#1972
- kubeedge/kubeedge#1974
- kubeedge/kubeedge#3220
- kubeedge/kubeedge#3234
- kubeedge/kubeedge#3086
- kubeedge/kubeedge#3829

- Issues responded to:
- kubeedge/kubeedge#3959

[community membership guidelines]: https://github.com/kubeedge/community/blob/master/community-membership.md
[mailing list]: https://groups.google.com/forum/#!forum/kubeedge
[slack]: https://kubeedge.slack.com/
[watchers list]: https://github.com/kubeedge/kubeedge/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication
[devstats]: https://kubeedge.devstats.cncf.io/d/56/company-commits-table?orgId=1
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please check your email or visit [@kubeedge](https://github.com/kubeedge) to confirm and join
