### ISSUE TITLE
REQUEST: New membership for ls889

### ISSUE THREAD

**Issue by ls889** [kubeedge/community#9]
## GitHub Username

[@ls889](https://github.com/ls889)

## Organization you are requesting membership in

[@kubeedge](https://github.com/kubeedge)

## Requirements

* [x]  I have reviewed the [community membership guidelines](https://github.com/kubeedge/community/blob/master/community-membership.md)
* [x]  I have enabled [two-factor authentication](https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication) on my GitHub account
* [x]  I am actively contributing to 1 or more KubeEdge subprojects
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## Sponsors

[@fisherxu](https://github.com/fisherxu)
[@kevin-wangzefeng](https://github.com/kevin-wangzefeng)

## List of contributions to the KubeEdge project

- PRs reviewed / authored:
  [kubeedge/kubeedge#1443](https://github.com/kubeedge/kubeedge/pull/1443)
  [kubeedge/kubeedge#1645](https://github.com/kubeedge/kubeedge/pull/1645)
  [kubeedge/kubeedge#1651](https://github.com/kubeedge/kubeedge/pull/1651)
  [kubeedge/kubeedge#1652](https://github.com/kubeedge/kubeedge/pull/1652)
  [fisherxu/kubeedge#8](https://github.com/fisherxu/kubeedge/pull/8)
  [fisherxu/kubeedge#10](https://github.com/fisherxu/kubeedge/pull/10)

**Comment by fisherxu** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, looking forward to more of your contributions.

**Comment by ls889** [comment]
@kevin-wangzefeng Thanks! It is my honor, I will work harder.
